package org.bbaw.wsp.cms.document;

import java.util.HashMap;

public class SubjectHandler {
  private static SubjectHandler instance;
  private static HashMap<String, String> ddcSubject2Code = new HashMap<String, String>();
  private static HashMap<String, String> ddcCode2Subject = new HashMap<String, String>();
  
  public static SubjectHandler getInstance() {
    if (instance == null) {
      instance = new SubjectHandler();
      instance.init();
    }
    return instance;
  }

  private void init() {
    ddcSubject2Code.put("Allgemeines, Wissenschaft", "000");
    ddcSubject2Code.put("Informatik", "004");
    ddcSubject2Code.put("Bibliografien", "010");
    ddcSubject2Code.put("Bibliotheks- und Informationswissenschaft", "020"); 
    ddcSubject2Code.put("Enzyklopädien", "030");
    ddcSubject2Code.put("Zeitschriften, fortlaufende Sammelwerke", "050"); 
    ddcSubject2Code.put("Organisationen, Museumswissenschaft", "060");
    ddcSubject2Code.put("Nachrichtenmedien, Journalismus, Verlagswesen", ""); 
    ddcSubject2Code.put("Allgemeine Sammelwerke", "070");
    ddcSubject2Code.put("Handschriften, seltene Bücher", "080"); 
    ddcSubject2Code.put("Philosophie", "090");
    ddcSubject2Code.put("Parapsychologie, Okkultismus", "130");
    ddcSubject2Code.put("Psychologie", "150");
    ddcSubject2Code.put("Religion, Religionsphilosophie", "200");
    ddcSubject2Code.put("Bibel", "220");
    ddcSubject2Code.put("Theologie, Christentum", "230");
    ddcSubject2Code.put("Andere Religionen", "290");
    ddcSubject2Code.put("Sozialwissenschaften, Soziologie", "300");
    ddcSubject2Code.put("Statistik", "310");
    ddcSubject2Code.put("Politik", "320");
    ddcSubject2Code.put("Wirtschaft", "330");
    ddcSubject2Code.put("Recht", "340");
    ddcSubject2Code.put("Öffentliche Verwaltung", "350");
    ddcSubject2Code.put("Militär", "355");
    ddcSubject2Code.put("Soziale Probleme, Sozialarbeit", "360");
    ddcSubject2Code.put("Erziehung, Schul- und Bildungswesen", "370");
    ddcSubject2Code.put("Handel, Kommunikation, Verkehr", "380");
    ddcSubject2Code.put("Ethnologie", "390");
    ddcSubject2Code.put("Sprachwissenschaft, Linguistik", "400");
    ddcSubject2Code.put("Englisch", "420");
    ddcSubject2Code.put("Deutsch", "430");
    ddcSubject2Code.put("Andere germanische Sprachen", "439");
    ddcSubject2Code.put("Französisch, romanische Sprachen allgemein", "440");
    ddcSubject2Code.put("Italienisch, Rumänisch, Rätoromanisch", "");
    ddcSubject2Code.put("Spanisch, Portugiesisch", "460");
    ddcSubject2Code.put("Latein", "470");
    ddcSubject2Code.put("Griechisch", "480");
    ddcSubject2Code.put("Andere Sprachen", "490");
    ddcSubject2Code.put("Naturwissenschaften", "500");
    ddcSubject2Code.put("Mathematik", "510");
    ddcSubject2Code.put("Astronomie", "520");
    ddcSubject2Code.put("Physik", "530");
    ddcSubject2Code.put("Chemie", "540");
    ddcSubject2Code.put("Geowissenschaften", "550");
    ddcSubject2Code.put("Paläontologie", "560");
    ddcSubject2Code.put("Biowissenschaften, Biologie", "570");
    ddcSubject2Code.put("Pflanzen (Botanik)", "580");
    ddcSubject2Code.put("Tiere (Zoologie)", "590");
    ddcSubject2Code.put("Technik", "600");
    ddcSubject2Code.put("Medizin", "610");
    ddcSubject2Code.put("Ingenieurwissenschaften", "620");
    ddcSubject2Code.put("Landwirtschaft, Veterinärmedizin", "630");
    ddcSubject2Code.put("Hauswirtschaft", "640");
    ddcSubject2Code.put("Management", "650");
    ddcSubject2Code.put("Technische Chemie", "660");
    ddcSubject2Code.put("Industrielle Fertigung", "670");
    ddcSubject2Code.put("Hausbau, Bauhandwerk", "690");
    ddcSubject2Code.put("Künste, Bildende Kunst allgemein", "700");
    ddcSubject2Code.put("Landschaftsgestaltung, Raumplanung", "710");
    ddcSubject2Code.put("Architektur", "720");
    ddcSubject2Code.put("Plastik, Numismatik, Keramik, Metallkunst", "730");
    ddcSubject2Code.put("Zeichnung, Kunsthandwerk", "");
    ddcSubject2Code.put("Comics, Cartoons, Karikaturen", "741.5");
    ddcSubject2Code.put("Malerei", "750");
    ddcSubject2Code.put("Grafische Verfahren, Drucke", "760");
    ddcSubject2Code.put("Fotografie, Computerkunst", "770");
    ddcSubject2Code.put("Musik", "780");
    ddcSubject2Code.put("Freizeitgestaltung, Darstellende Kunst", "790");
    ddcSubject2Code.put("Öffentliche Darbietungen, Film, Rundfunk", "791");
    ddcSubject2Code.put("Theater, Tanz", "792");
    ddcSubject2Code.put("Spiel", "793");
    ddcSubject2Code.put("Sport", "796");
    ddcSubject2Code.put("Literatur, Rhetorik, Literaturwissenschaft", "800");
    ddcSubject2Code.put("Englische Literatur Amerikas", "810");
    ddcSubject2Code.put("Englische Literatur", "820");
    ddcSubject2Code.put("Deutsche Literatur", "830");
    ddcSubject2Code.put("Literatur in anderen germanischen Sprachen", "839");
    ddcSubject2Code.put("Französische Literatur", "840");
    ddcSubject2Code.put("Italienische, rumänische, rätoromanische Literatur", "850");
    ddcSubject2Code.put("Spanische und portugiesische Literatur", "860");
    ddcSubject2Code.put("Lateinische Literatur", "870");
    ddcSubject2Code.put("Griechische Literatur", "880");
    ddcSubject2Code.put("Literatur in anderen Sprachen", "890");
    ddcSubject2Code.put("Geschichte", "900");
    ddcSubject2Code.put("Geografie, Reisen", "910");
    ddcSubject2Code.put("Landeskunde Deutschlands", "914.3");
    ddcSubject2Code.put("Biografie, Genealogie, Heraldik", "920");
    ddcSubject2Code.put("Alte Geschichte, Archäologie", "930");
    ddcSubject2Code.put("Geschichte Europas", "940");
    ddcSubject2Code.put("Geschichte Deutschlands", "943");
    ddcSubject2Code.put("Geschichte Asiens", "950");
    ddcSubject2Code.put("Geschichte Afrikas", "960");
    ddcSubject2Code.put("Geschichte Nordamerikas", "970");
    ddcSubject2Code.put("Geschichte Südamerikas", "980");
    ddcSubject2Code.put("Geschichte der übrigen Welt", "990");
    
    ddcCode2Subject.put("000", "Allgemeines, Wissenschaft");
    ddcCode2Subject.put("004", "Informatik");
    ddcCode2Subject.put("010", "Bibliografien");
    ddcCode2Subject.put("020", "Bibliotheks- und Informationswissenschaft"); 
    ddcCode2Subject.put("030", "Enzyklopädien");
    ddcCode2Subject.put("050", "Zeitschriften, fortlaufende Sammelwerke"); 
    ddcCode2Subject.put("060", "Organisationen, Museumswissenschaft");
    ddcCode2Subject.put("070", "Nachrichtenmedien, Journalismus, Verlagswesen"); 
    ddcCode2Subject.put("080", "Allgemeine Sammelwerke");
    ddcCode2Subject.put("090", "Handschriften, seltene Bücher"); 
    ddcCode2Subject.put("100", "Philosophie");
    ddcCode2Subject.put("130", "Parapsychologie, Okkultismus");
    ddcCode2Subject.put("150", "Psychologie");
    ddcCode2Subject.put("200", "Religion, Religionsphilosophie");
    ddcCode2Subject.put("220", "Bibel");
    ddcCode2Subject.put("230", "Theologie, Christentum");
    ddcCode2Subject.put("290", "Andere Religionen");
    ddcCode2Subject.put("300", "Sozialwissenschaften, Soziologie");
    ddcCode2Subject.put("310", "Statistik");
    ddcCode2Subject.put("320", "Politik");
    ddcCode2Subject.put("330", "Wirtschaft");
    ddcCode2Subject.put("340", "Recht");
    ddcCode2Subject.put("350", "Öffentliche Verwaltung");
    ddcCode2Subject.put("355", "Militär");
    ddcCode2Subject.put("360", "Soziale Probleme, Sozialarbeit");
    ddcCode2Subject.put("370", "Erziehung, Schul- und Bildungswesen");
    ddcCode2Subject.put("380", "Handel, Kommunikation, Verkehr");
    ddcCode2Subject.put("390", "Ethnologie");
    ddcCode2Subject.put("400", "Sprachwissenschaft, Linguistik");
    ddcCode2Subject.put("420", "Englisch");
    ddcCode2Subject.put("430", "Deutsch");
    ddcCode2Subject.put("439", "Andere germanische Sprachen");
    ddcCode2Subject.put("440", "Französisch, romanische Sprachen allgemein");
    ddcCode2Subject.put("450", "Italienisch, Rumänisch, Rätoromanisch");
    ddcCode2Subject.put("460", "Spanisch, Portugiesisch");
    ddcCode2Subject.put("470", "Latein");
    ddcCode2Subject.put("480", "Griechisch");
    ddcCode2Subject.put("490", "Andere Sprachen");
    ddcCode2Subject.put("500", "Naturwissenschaften");
    ddcCode2Subject.put("510", "Mathematik");
    ddcCode2Subject.put("520", "Astronomie");
    ddcCode2Subject.put("530", "Physik");
    ddcCode2Subject.put("540", "Chemie");
    ddcCode2Subject.put("550", "Geowissenschaften");
    ddcCode2Subject.put("560", "Paläontologie");
    ddcCode2Subject.put("570", "Biowissenschaften, Biologie");
    ddcCode2Subject.put("580", "Pflanzen (Botanik)");
    ddcCode2Subject.put("590", "Tiere (Zoologie)");
    ddcCode2Subject.put("600", "Technik");
    ddcCode2Subject.put("610", "Medizin");
    ddcCode2Subject.put("620", "Ingenieurwissenschaften");
    ddcCode2Subject.put("630", "Landwirtschaft, Veterinärmedizin");
    ddcCode2Subject.put("640", "Hauswirtschaft");
    ddcCode2Subject.put("650", "Management");
    ddcCode2Subject.put("660", "Technische Chemie");
    ddcCode2Subject.put("670", "Industrielle Fertigung");
    ddcCode2Subject.put("690", "Hausbau, Bauhandwerk");
    ddcCode2Subject.put("700", "Künste, Bildende Kunst allgemein");
    ddcCode2Subject.put("710", "Landschaftsgestaltung, Raumplanung");
    ddcCode2Subject.put("720", "Architektur");
    ddcCode2Subject.put("730", "Plastik, Numismatik, Keramik, Metallkunst");
    ddcCode2Subject.put("740", "Zeichnung, Kunsthandwerk");
    ddcCode2Subject.put("741.5", "Comics, Cartoons, Karikaturen");
    ddcCode2Subject.put("750", "Malerei");
    ddcCode2Subject.put("760", "Grafische Verfahren, Drucke");
    ddcCode2Subject.put("770", "Fotografie, Computerkunst");
    ddcCode2Subject.put("780", "Musik");
    ddcCode2Subject.put("790", "Freizeitgestaltung, Darstellende Kunst");
    ddcCode2Subject.put("791", "Öffentliche Darbietungen, Film, Rundfunk");
    ddcCode2Subject.put("792", "Theater, Tanz");
    ddcCode2Subject.put("793", "Spiel");
    ddcCode2Subject.put("796", "Sport");
    ddcCode2Subject.put("800", "Literatur, Rhetorik, Literaturwissenschaft");
    ddcCode2Subject.put("810", "Englische Literatur Amerikas");
    ddcCode2Subject.put("820", "Englische Literatur");
    ddcCode2Subject.put("830", "Deutsche Literatur");
    ddcCode2Subject.put("839", "Literatur in anderen germanischen Sprachen");
    ddcCode2Subject.put("840", "Französische Literatur");
    ddcCode2Subject.put("850", "Italienische, rumänische, rätoromanische Literatur");
    ddcCode2Subject.put("860", "Spanische und portugiesische Literatur");
    ddcCode2Subject.put("870", "Lateinische Literatur");
    ddcCode2Subject.put("880", "Griechische Literatur");
    ddcCode2Subject.put("890", "Literatur in anderen Sprachen");
    ddcCode2Subject.put("900", "Geschichte");
    ddcCode2Subject.put("910", "Geografie, Reisen");
    ddcCode2Subject.put("914.3", "Landeskunde Deutschlands");
    ddcCode2Subject.put("920", "Biografie, Genealogie, Heraldik");
    ddcCode2Subject.put("930", "Alte Geschichte, Archäologie");
    ddcCode2Subject.put("940", "Geschichte Europas");
    ddcCode2Subject.put("943", "Geschichte Deutschlands");
    ddcCode2Subject.put("950", "Geschichte Asiens");
    ddcCode2Subject.put("960", "Geschichte Afrikas");
    ddcCode2Subject.put("970", "Geschichte Nordamerikas");
    ddcCode2Subject.put("980", "Geschichte Südamerikas");
    ddcCode2Subject.put("990", "Geschichte der übrigen Welt");

    
  }
  
  public String getDdcCode(String ddcSubjectStr) {
    return ddcSubject2Code.get(ddcSubjectStr);
  }
  
  public String getDdcSubject(String ddcCode) {
    return ddcCode2Subject.get(ddcCode);
  }
}